# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 12:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unsafe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unsafeuser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='unsafeuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='unsafeuser',
            name='username',
        ),
        migrations.AddField(
            model_name='unsafeuser',
            name='plaintext_password',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unsafeuser',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
