# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_module', '0003_auto_20160102_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(max_length=200, verbose_name=b'text'),
        ),
    ]
